#!/usr/bin/expect -f
log_user 0
set ORACLE_KEY_PASSWD [lindex $argv 0]
spawn docker exec -ti aut_client  /root/.local/bin/aut account new
expect -re "Password for new account: "
send -- "$ORACLE_KEY_PASSWD\r"
expect -re "Confirm account password: "
send -- "$ORACLE_KEY_PASSWD\r"
expect -re {/root/.autonity/keystore/(.*)}
puts "$expect_out(1,string)"
#sleep 4
