#!/bin/bash
ROOT_PATH=$( dirname -- "$( readlink -f -- "$0"; )"; );

source $ROOT_PATH/../.env
source $ROOT_PATH/../.PACKAGE_USE

echo -e "\033[0;33m ♨ Generation Oracle key for  Autonity WITH password from .env  \033[0m\n"


GENERATION_RESULT=`$ROOT_PATH/includes/generate_account $ORACLE_KEY_PASSWD | tr -d $'\r'`
#echo "OLD $ORACLE_UTC_FILE"
FINAL_FILENAME="oracle.key"
mv "$ROOT_PATH/../.data/.autonity/keystore/${GENERATION_RESULT}" "$ROOT_PATH/../.data/.autonity/keystore/${FINAL_FILENAME}"
echo -e "Generated wallet: ${FINAL_FILENAME}\n"

echo "ORACLE_UTC_FILE=\"${FINAL_FILENAME}\"" >> $ROOT_PATH/../.env

#bash $ROOT_PATH/generate_indexer_handbook

DECODED_WALLET_DATA=`docker exec -ti aut_client  /usr/local/bin/web3  account extract --keyfile=/root/.autonity/keystore/${FINAL_FILENAME} --password ${ORACLE_KEY_PASSWD}`
bash $ROOT_PATH/generate_indexer_handbook

echo -e "\n\n\n\nGenerated wallet: ${FINAL_FILENAME}\n"
echo -e "Wallet details: \n\n ${DECODED_WALLET_DATA}\n\n"

echo -e "\n\n Please run start autonity again. You ORACLE_UTC_FILE in  .env updated"
