#!/bin/bash
ROOT_PATH=$( dirname -- "$( readlink -f -- "$0"; )"; );

set -a
source $ROOT_PATH/../.env
source $ROOT_PATH/../.PACKAGE_USE
set -a

echo -e "\033[0;33m ♨ Generation Oracle key for  Autonity WITH password from .env  \033[0m\n"


GENERATION_RESULT=`$ROOT_PATH/includes/generate_account $ORACLE_KEY_PASSWD`


echo -e "Generated wallet: ${GENERATION_RESULT}\n"
echo "keyfile = /root/.autonity/keystore/${GENERATION_RESULT}" >> $ROOT_PATH/../.data/.autonity/.autrc

bash $ROOT_PATH/generate_indexer_handbook
