#!/bin/bash
ROOT_PATH=$( dirname -- "$( readlink -f -- "$0"; )"; );

set -a
source $ROOT_PATH/../.env
source $ROOT_PATH/../.PACKAGE_USE
set -a

echo -e "\033[0;33m ♨ Account generation  \033[0m\n"

read -p ' ^|^m Enter new account password: ' input_password

while [ "$input_password" == "" ]
do
  echo -e "\033[0;31m   ^|^x Incorrect password. \033[0m \n"
  read -p ' ^|^m Enter new account password: ' input_password
done



read -p ' ^|^m Enter password again: ' input_password2

while [ "$input_password2" != "$input_password" ]
do
  echo -e "\033[0;31m   ^|^x Incorrect password confirmation. \033[0m \n"
  read -p ' ^|^m Enter password again: ' input_password2
done



if [[ -z "$1" ]];
then
read -p ' ^|^m Enter account name: ' input_name

while [ "$input_name" == "" ]
do
  echo -e "\033[0;31m   ^|^x Incorrect account name. \033[0m \n"
  read -p ' ^|^m Enter account name: ' input_name
done
else
input_name=$1
fi

GENERATION_RESULT=`$ROOT_PATH/includes/generate_account $input_password | tr -d $'\r'`

FINAL_FILENAME=$input_name
mv "$ROOT_PATH/../.data/.autonity/keystore/${GENERATION_RESULT}" "$ROOT_PATH/../.data/.autonity/keystore/${FINAL_FILENAME}"

if [ ! -f "$ROOT_PATH/../.data/.autonity/.autrc" ]; then
    cp $ROOT_PATH/../.data/.autonity/.autrc.template $ROOT_PATH/../.data/.autonity/.autrc
    echo "keyfile = /root/.autonity/keystore/${FINAL_FILENAME}" >> $ROOT_PATH/../.data/.autonity/.autrc
fi

DECODED_WALLET_DATA=`docker exec -ti aut_client  /usr/local/bin/web3  account extract --keyfile=/root/.autonity/keystore/${FINAL_FILENAME} --password ${input_password}`
PRIVATE_KEY=`docker exec -ti aut_client  /usr/local/bin/web3  account extract --keyfile=/root/.autonity/keystore/${FINAL_FILENAME} --password ${input_password} | sed -n -e 's/^.*Private key: //p' |  tr -d $'\r' | cut -c3-`
PUBLIC_KEY=`docker exec -ti aut_client  /usr/local/bin/web3  account extract --keyfile=/root/.autonity/keystore/${FINAL_FILENAME} --password ${input_password} | sed -n -e 's/^.*Public address: //p' |  tr -d $'\r' `

echo "$PRIVATE_KEY" >  "$ROOT_PATH/../.data/.autonity/${FINAL_FILENAME}.private"
echo "$PUBLIC_KEY" >  "$ROOT_PATH/../.data/.autonity/${FINAL_FILENAME}.public"

bash $ROOT_PATH/generate_indexer_handbook

echo -e "\n\n\n\nGenerated wallet: ${FINAL_FILENAME}\n"
echo -e "Wallet details: \n\n ${DECODED_WALLET_DATA}"
#bash $ROOT_PATH/generate_indexer_handbook
