#!/bin/bash

ROOT_PATH=$( dirname -- "$( readlink -f -- "$0"; )"; );

if [ ! -f "$ROOT_PATH/../.env" ]; then

  cp  $ROOT_PATH/../.env.default $ROOT_PATH/../.env
  geneeatedKey=`tr -dc A-Za-z0-9 </dev/urandom | head -c 13; echo`
  sed -i "s/TESTPASSWORD/${geneeatedKey}/"  $ROOT_PATH/../.env

  geneeatedKey=`tr -dc A-Za-z0-9 </dev/urandom | head -c 17; echo`
  sed -i "s/REPLACE_ME/${geneeatedKey}/"  $ROOT_PATH/../.env

  echo -e ".env file generated"
else
  echo -e ".env File already exists. Override protected"
fi

