#!/bin/bash

ROOT_PATH=$( dirname -- "$( readlink -f -- "$0"; )"; );

cp $ROOT_PATH/../.data/autonity_node_rpc/autonity/autonitykeys  $ROOT_PATH/../.data/.autonity/autonitykeys.private

aut account import-private-key /root/.autonity/nodekey_rpc.private --keyfile /root/.autonity/keystore/nodekey_rpc --keystore /root/.autonity/keystore
