#!/bin/bash

if [[ -z "$1" ]];
then
node_container="autonity"
else
node_container=$1
fi

PROJECTS_LIST=`curl -s 'https://validators.game.autonity.org/api/ds/query' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Origin: https://validators.game.autonity.org' \
  -H 'Referer: https://validators.game.autonity.org/d/iaqkN61Vk/validators?orgId=1&refresh=30m' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'x-grafana-org-id: 1' \
  --data-raw '{"queries":[{"refId":"A","datasource":{"uid":"jdD9V614z","type":"postgres"},"rawSql":"  select * from piccadilly_65100004.validators_with_username_view_r4;","format":"table","datasourceId":6,"intervalMs":60000,"maxDataPoints":1306}],"range":{"from":"2024-12-09T11:11:08.479Z","to":"2025-12-13T17:11:08.479Z","raw":{"from":"now-6h","to":"now"}},"from":"1702465868479","to":"1702487468479"}'`


readarray -t conversations < <(echo $PROJECTS_LIST | tr -d '\n' | tr -d '\n'  | jq -rc  ".results.A.frames[0].data.values[0] | map(. | fromjson) | map(.enode) | .[]")
for conversation in "${conversations[@]}"; do
echo "Adding: $conversation"

/usr/bin/expect <<EOD
spawn docker exec -ti $node_container autonity attach /autonity-chaindata/autonity.ipc
expect "To exit, press ctrl-d or type exit"
#sleep 2
send -- admin.addPeer("$conversation")\n
expect "true"

exit
EOD

done
